### ISSUE TITLE
PyPI publish workflow need update

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#1493]
during https://github.com/Kozea/Radicale/issues/1483 it was found that the workflow causes some warnings related to legacy/outdated, can one investigate and support please?

**Comment by gentooboontoo** [comment]
@pbiering I pushed 2 commits to `master` to update versions of actions. It should fix some warnings.

**Comment by pbiering** [comment]
@gentooboontoo : looks like there is still an issue, can you investigate why the publish workflow for 3.2.1 was not successful?
https://github.com/Kozea/Radicale/actions/runs/9337496322

**Comment by pbiering** [comment]
`.github/workflows/pypi-publish.yml` updated, tag `v3.2.1` moved, but the action is still pinned to an older commit. Does anyone know how to trigger the workflow with the commit related to current `v3.2.1` tag without creating a new release?

**Comment by dotlambda** [comment]
> Does anyone know how to trigger the workflow with the commit related to current `v3.2.1` tag without creating a new release?

Don't do it. If it's been released it shouldn't be changed. Just create a new release 3.2.2.

**Comment by gentooboontoo** [comment]
> @gentooboontoo : looks like there is still an issue, can you investigate why the publish workflow for 3.2.1 was not successful?
https://github.com/Kozea/Radicale/actions/runs/9337496322

Sorry I forgot the required field you have then added in your fix. I think it should work now by triggering a new release 3.2.2 as suggested by @dotlambda.

**Comment by gentooboontoo** [comment]
@pbiering fyi I moved back `v3.2.1` tag to previous commit hoping it could solve #1508. Thank you very much for your time and work :)

**Comment by pbiering** [comment]
@gentooboontoo : thank you very much, publish was now successful: https://pypi.org/project/Radicale/#history

BTW: used only a pre-release "3.2.1-pypi" for that trigger, as no code change was done.
