### ISSUE TITLE
HTTP Error 500 when trying to sync with Thunderbird

### ISSUE THREAD

**Issue by lucky62** [Kozea/Radicale#1820]
Hello, I am getting HTTP error 500 when trying to sync Thunderbird with Radicale.
I set the logging to debug and grabbed some details (attached).

[Radicale_Error.txt](https://github.com/user-attachments/files/21204188/Radicale_Error.txt)

Radicale installed on Proxmox using [script](https://community-scripts.github.io/ProxmoxVE/scripts?id=radicale).

**Comment by pbiering** [comment]
```
[2025-07-13 13:12:47 +0200] [402/Thread-6 (process_request_thread)] [ERROR] An exception occurred during REPORT request on '/someuser/0a1bd8a7-7b8d-130e-9979-d23b5e0acb39/': vevent_list
Traceback (most recent call last):
  File "/opt/radicale/lib/python3.11/site-packages/vobject/base.py", line 531, in __getattr__
    return self.contents[toVName(name, 5)]
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'vevent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/radicale/lib/python3.11/site-packages/radicale/app/__init__.py", line 129, in __call__
    status_text, headers, answers = self._handle_request(environ)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/radicale/lib/python3.11/site-packages/radicale/app/__init__.py", line 352, in _handle_request
    status, headers, answer = function(
                              ^^^^^^^^^
  File "/opt/radicale/lib/python3.11/site-packages/radicale/app/report.py", line 777, in do_REPORT
    status, xml_answer = xml_report(
                         ^^^^^^^^^^^
  File "/opt/radicale/lib/python3.11/site-packages/radicale/app/report.py", line 313, in xml_report
    n_vevents += len(item.vobject_item.vevent_list)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/radicale/lib/python3.11/site-packages/vobject/base.py", line 535, in __getattr__
    raise AttributeError(name)
```

This looks like related to https://github.com/Kozea/Radicale/pull/1815 triggered by https://github.com/Kozea/Radicale/issues/1812 

@lbt / @metallerok - can you please look into

@lucky62 - can you confirm this is not an issue with release 3.5.4?

**Comment by lbt** [comment]
This should fix it: https://github.com/lbt/Radicale/tree/issue1820

I'll run a few more checks locally and then issue a PR

**Comment by pbiering** [comment]
@lucky62 - please try lastest upstream and reopen, if issue still persists

**Comment by lucky62** [comment]
3.5.4 is working normally.
