### ISSUE TITLE
DELETE notworking ?

### ISSUE THREAD

**Issue by alci63** [Kozea/Radicale#394]
I am using Radicale (1.1.1) on a Ubuntu server, with Thunderbird as a client.
My problem is I can't DELETE any event.
Looking at the logs, I can see a DELETE request on the item, immediately followed by a HEAD request.
No error message. But when looking into the ics file, the event is still there. On the client side, the event is not deleted either...

**Comment by alci63** [comment]
I did set the log level to debug, and get this:

```
2016-05-10 10:26:11,586 - INFO: DELETE request at /myuser/fro.ics/0152-4ceb-ac52-a5fd9fc249f9.ics received
2016-05-10 10:26:11,588 - DEBUG: Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_CHARSET': 'utf-8,*;q=0.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3',
 'HTTP_AUTHORIZATION': 'Basic ZnJvdXRpZXI6I2Jyb3UzdHQzJA==',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'Keep-Alive',
 'HTTP_HOST': '10.0.0.1:5232',
 'HTTP_IF_MATCH': '"6d5d4fd9060a8d8e09190d91287c9d48"',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Thunderbird/38.7.2 Lightning/4.0.5.2',
 'HTTP_X_FORWARDED_FOR': '10.0.0.75',
 'HTTP_X_FORWARDED_HOST': 'mydomain.net',
 'HTTP_X_FORWARDED_SERVER': 'mydomain.net',
 'PATH_INFO': '/myuser/fro.ics/0152-4ceb-ac52-a5fd9fc249f9.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '192.168.1.11',
 'REMOTE_HOST': 'mydomain.com',
 'REQUEST_METHOD': 'DELETE',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'radicale.mydomain.net',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7.11+',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7fdde42561e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x7fdde2358b48>,
 'wsgi.input': <socket._fileobject object at 0x7fdde22d5c50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2016-05-10 10:26:11,588 - DEBUG: Sanitized path: /myuser/fro.ics/0152-4ceb-ac52-a5fd9fc249f9.ics
2016-05-10 10:26:11,590 - DEBUG: LDAP bind for uid=myuser in base ou=users,dc=mydomain,dc=net
2016-05-10 10:26:11,590 - DEBUG: Used LDAP filter: uid=myuser
2016-05-10 10:26:11,591 - DEBUG: User myuser found
2016-05-10 10:26:11,592 - DEBUG: LDAP bind OK
2016-05-10 10:26:11,592 - DEBUG: Rights type 'owner_write'
2016-05-10 10:26:11,593 - DEBUG: Test if 'myuser:myuser/fro.ics' matches against '.+:^myuser(/.*)?$' from section 'w'
2016-05-10 10:26:11,593 - DEBUG: Section 'w' matches
2016-05-10 10:26:11,593 - DEBUG: myuser has read access to collection myuser/fro.ics/
2016-05-10 10:26:11,593 - DEBUG: Rights type 'owner_write'
2016-05-10 10:26:11,593 - DEBUG: Test if 'myuser:myuser/fro.ics' matches against '.+:^myuser(/.*)?$' from section 'w'
2016-05-10 10:26:11,593 - DEBUG: Section 'w' matches
2016-05-10 10:26:11,593 - DEBUG: myuser has write access to collection myuser/fro.ics/
2016-05-10 10:26:11,595 - DEBUG: Answer status: 412 Precondition Failed
```

Notice the final answer: 412 Precondition Failed.

**Comment by liZe** [comment]
@alci63 Do you use the multifilesystem storage?

**Comment by alci63** [comment]
@liZe no I don't. I'm using the default 'filesystem' storage (in /var/lib/radicale/collections)

**Comment by liZe** [comment]
Well, then I don't know why you get 412s. If Thunderbird uses HEAD requests to get etags, it's possible that this bug is fixed by 6be7dab. Could you try to use the 1.1.x branch please? If it fixes your problem, I'll release a new version.

**Comment by alci63** [comment]
Ok, I've checked 1.1.x branch out, and copied files in Radicale/radicale into /usr/lib/python2.7/dist-packages/radicale/. Then I restarted the server.

Result is the same, iI still get error 412.

Is there a way I can confirm my upgrade is ok (ie I'm really running the branch code) ?

**Comment by liZe** [comment]
> Is there a way I can confirm my upgrade is ok (ie I'm really running the branch code) ?

You don't need to install Radicale. Downloading Radicale in a separate folder, going into that folder in your shell and launching `./radicale.py` should be enough, even if you have another version installed.

Is it possible to have your calendar (if nothing's too personal) and the logs of the failing DELETE request corresponding to that calendar? It's even better if you can reproduce the problem with a new calendar.

**Comment by maximilianosbrocca-santex** [comment]
Hello... I've also installed version 1.1.1 in my server. In my case, we are adding/updating events from an application, and Users Calendar Clients will just have read only rights. So, for example, we are putting the new events or updates from java code client.

Now I'm researching that is possible to delete events. So, I'm working in our app code, so when an event is deleted, I want also to delete it from caldav server. I'm executing DELETE call using a REST client (Postman Rest Client) and I'm getting the **412 Precondition Failed** error. I enabled DEBUG mode, and  this is what I'm seeing on the logs (same as debug = False):

```
2016-07-28 14:01:20,740 - INFO: DELETE request at /calendar/dav/ff5d7a335369b4162522f5d29ef28069a0ffaa20ed8012cdf8711ccd9b735a1b/events/13.ics received
2016-07-28 14:01:20,741 - DEBUG: Request headers:
{'CONTENT_LENGTH': '',
 'CONTENT_TYPE': 'text/plain',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': '*/*',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, sdch',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.8,es;q=0.6',
 'HTTP_AUTHORIZATION': 'Basic ffaa20ed8012cdf8711ccd9b735a1b=',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_HOST': 'ec2-54-68-232-137.us-west-2.compute.amazonaws.com:5232',
 'HTTP_ORIGIN': 'chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop',
 'HTTP_POSTMAN_TOKEN': '550e0b81-e28b-4e0b-e316-31117920f099',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36',
 'PATH_INFO': '/calendar/dav/ff5d7a335369b4162522f5d29ef28069a0ffaa20ed8012cdf8711ccd9b735a1b/events/13.ics',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '190.210.94.116',
 'REMOTE_HOST': 'customer-static-210-94-116.iplannetworks.net',
 'REQUEST_METHOD': 'DELETE',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'ip-172-31-45-248.us-west-2.compute.internal',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.6.9',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x7f233fd761e0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0xc1de90>,
 'wsgi.input': <socket._fileobject object at 0xd81f50>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
2016-07-28 14:01:20,742 - DEBUG: Sanitized path: /calendar/dav/ff5d7a335369b4162522f5d29ef28069a0ffaa20ed8012cdf8711ccd9b735a1b/events/13.ics
2016-07-28 14:01:20,742 - DEBUG: ADMIN_USER has read access to collection calendar/dav/ff5d7a335369b4162522f5d29ef28069a0ffaa20ed8012cdf8711ccd9b735a1b/events/13/
2016-07-28 14:01:20,742 - DEBUG: ADMIN_USER has write access to collection calendar/dav/ff5d7a335369b4162522f5d29ef28069a0ffaa20ed8012cdf8711ccd9b735a1b/events/13/
2016-07-28 14:01:20,743 - DEBUG: Answer status: 412 Precondition Failed
```

@liZe 
Could you please help me to figure out which could be the issue? Or help me to figure out if I'm doing something wrong.

**Comment by liZe** [comment]
> I'm executing DELETE call using a REST client (Postman Rest Client) and I'm getting the 412 Precondition Failed error.

@maximilianosbrocca-santex your problem is different from the one described in this ticket. To remove a collection, you have to add a trailing slash to the URL (`/calendar/dav/…/events/13.ics/` instead of `/calendar/dav/…/events/13.ics`). It's caused by Radicale's awful magic to detect collections, and it's fixed for future 2.0 version.

@alci63 is your problem solved? If not, is it possible to have a copy of your calendar?

**Comment by maximilianosbrocca-santex** [comment]
Thank you very much @liZe for the information!

**Comment by pbiering** [comment]
old bug, please reopen if reproducable with newer version
