### ISSUE TITLE
CalDavSynchronizer/2.7 / Discovery / TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by pbiering** [Kozea/Radicale#532]
CalDavSynchronizer/2.7 error 500 occurs during "Test or discover setting":

Request header (the important lines):

```
 'HTTP_DEPTH': '0',
 'PATH_INFO': '/user/calendar.ics/',
```

Request content:

```
<?xml version='1.0'?>
                        <D:propfind xmlns:D="DAV:">
                            <D:allprop/>
                        </D:propfind>
```

Response (2.0.0rc):

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/lib/python3.4/site-packages/radicale/__init__.py", line 411, in __call__
    status, headers, answer = function(environ, path, user)
  File "/usr/lib/python3.4/site-packages/radicale/__init__.py", line 605, in do_PROPFIND
    path, content, read_items, write_items, user)
  File "/usr/lib/python3.4/site-packages/radicale/xmlutils.py", line 503, in propfind
    props = [prop.tag for prop in root.find(_tag("D", "prop"))]
TypeError: 'NoneType' object is not iterable
```

Tested on
- Radicale 2.0.0rc
- Radicale 0.10.0 (has same problem)

**Comment by liZe** [comment]
Hi!

Is this fixed with your merged pull requests?

**Comment by pbiering** [comment]
No, didn't solve this particular issue because it happen only during initial config and hit button "Test" instead of manual configuration, but it should be fixed somehow if it is a valid request with proper response (and here it's unclear to me what should be returned).

**Comment by Unrud** [comment]
Fixed in https://github.com/Kozea/Radicale/commit/b9db971060ae720822e007b40373928ff0d8508d
